version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.9

jobs:
  build:
    docker:
      - image: 'circleci/node'
    steps:
      - checkout
      - run: sudo apt-get install python-dev
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://schof.co'
          arguments: --acl public-read --cache-control "max-age=86400"
          overwrite: true
      - run: aws cloudfront create-invalidation --distribution-id EO1YEJXL0AGGJ --paths /\*

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
