name: Deploy

on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: use node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: install aws cli
      uses: chrislennon/action-aws-cli@1.1
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: upload to s3
      run: aws s3 sync "out" "s3://schof.co" --delete --acl public-read --cache-control "max-age=86400"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: invalidate cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id EO1YEJXL0AGGJ --paths /\*
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
