name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10]
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: use node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        CI: true
    - name: upload to s3
      uses: actions/aws/cli@master
      with:
        args: s3 sync "out" "s3://schof.co" --delete --acl public-read --cache-control "max-age=86400"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: invalidate cloudfront cache
      uses: actions/aws/cli@master
      with:
        args: cloudfront create-invalidation --distribution-id EO1YEJXL0AGGJ --paths /\*
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
