name: Proselint

on: [push]

jobs:
  proselint:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: install proselint
      run: |
        sudo add-apt-repository universe
        sudo apt install python3-proselint
    - name: run proselint
      run: proselint content/*/index.md
